### ISSUE TITLE
Export - option for mirroring sources directory tree

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#107]
This feature might be useful for IDE when exporting a project to a workspace.

This means we would copy all files for a project keeping the directory structure, set paths accordingly.

**Comment by aethaniel** [comment]
+1
As described this feature must be an option and not the normal behavior ;-)

**Comment by 0xc0170** [comment]
this should be resolved via #120, landed to dev_v0.6

**Comment by 0xc0170** [comment]
Ah, reopen, will be closed once v0.6 branch will be merged to master.
