### ISSUE TITLE
Organization project-generator

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#118]
Shall we move all repositories to the organization I created for pgen? This was one of the available options, so it's live: https://github.com/project-generator

There are already few of repostiories,and it will grow :smile_cat:
- pgen
- pgen definitions
- pgen tests
- pgen mbed example

I propose to do this change for v0.6, as it's breaking change, ppl will be required to update.

Suggestions anyone?

**Comment by matthewelse** [comment]
If you keep all of the repositories open as forks on your github then there's backwards compatibility

**Comment by 0xc0170** [comment]
True that ! Will do the next week

**Comment by 0xc0170** [comment]
@matthewelse Can you move tests there? Ill update travis to poin to a new loc, will fork it to fix the latest changes in the PR which is open

Pgen org needs a logo :)

**Comment by 0xc0170** [comment]
definitions and mbed example moved, pgen will follow soon with updates to all references.

**Comment by 0xc0170** [comment]
All repo were moved, project-generator donE !
