### ISSUE TITLE
Autocompletition for pgen commands

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#128]
As @matthewelse proposed for v0.6:

Add shell completion using https://github.com/kislyuk/argcomplete

**Comment by matthewelse** [comment]
I'll have a look at this this afternoon

**Comment by matthewelse** [comment]
There seems to be a problem using argcomplete on OS X I'll try it on Ubuntu and see what happens...

**Comment by 0xc0170** [comment]
Might not be multiplatform, closing this for now
