### ISSUE TITLE
Target debug/release

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#13]
There is not target currently defined. Should records define debug/release configuration?

**Comment by aethaniel** [comment]
+1, yes this is exactly what I'm facing at the moment.
On many cases, there are common definitions at project level and only some appropriate definitions according to targets. This can vary from one tool/IDE to another.

**Comment by 0xc0170** [comment]
At the moment, one target is for a project, the default one. We can discuss here how debug/release target can be implemented.

We should probably first simplify the records (somehow eliminate generic tools specific records).

**Comment by aethaniel** [comment]
This would certainly need to have sub-template (target) to be integrated after process into a main one (project).

**Comment by sg-** [comment]
My thoughts for simplicity sake is that the yaml descriptions should be configured for a release and while developing people should edit the project files as and when needed.

**Comment by 0xc0170** [comment]
I'll close this one. As the comment above. This would just complicate things with not much benefit (creating own debug/release projects is simple with just different settings).

**Comment by PeterWang19860926** [comment]
Is there any further update on this feature? supporting debug/release configure. I think this is a common feature when used with IDE: IAR, Keil etc
