### ISSUE TITLE
Export function needs .yaml files in project section

### ISSUE THREAD

**Issue by sarahmarshy** [project-generator/project_generator#146]
Would like to have the option to replace .yaml files with the attributes that they eventually reference 

Example:

projects:
    kl25z_blinky:
        - records/kl25z_cmsis.yaml
        - records/kl25z_target.yaml
        - records/kl25z_blinky.yaml

Instead of needing to open  - records/kl25z_blinky.yaml

Should be able to replace that with contents of  -records/kl25z_blinky.yaml

**Comment by 0xc0170** [comment]
What would be the use for this feature? How it would be invoked ?

**Comment by 0xc0170** [comment]
@sarahmarshy is this resolved?
