### ISSUE TITLE
Obj or lib sources

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#155]
I have consolidated sources recently for v0.6, and now thinking what we can do with

- source_files_obj
- source_files_lib

We probably can't make all into sources, as some libs might be without extension (although do we support  that?). I propose 3 solutions

1. All in sources - object files, libraries, source files (requires to fill proper extensions for us to group internally)
2. source_files_obj rename to object_files, source_files_lib to static_libraries
3. 1 and 2 combined - to resolve issue in the 1st one - using the second if needed. This would mean to keep both formats possible, which might be confusing. I would use the first one, and the second one would be used internally - once we sort sources to groups (source cpp, c, obj, libraries), we assing them to the proper keys - object_files and so on..

I vote for 3, with strong preference to use all in sources :-)

**Comment by sg-** [comment]
+1 I think all should be in sources

**Comment by sarahmarshy** [comment]
My latest commit puts all in sources

**Comment by sarahmarshy** [comment]
Removed "group_name" section in yaml

**Comment by sg-** [comment]
+1
