### ISSUE TITLE
Documentation - from wiki to gh pages?

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#164]
Github wiki is not ideal, therefore looking for options to make it more collaboration friendly. I'll update wiki to v0.6 version, as it will be the last one (v0.7 should be shipped with new structured docs)

First proposal - gh-pages, to have docs folder in this repo.

**Comment by matthewelse** [comment]
Yeah that sounds like a good plan - another possibility is readthedocs

**Comment by matthewelse** [comment]
@0xc0170 I think I'll have a look at moving the documentation to readthedocs

**Comment by matthewelse** [comment]
actually we could just use gh-pages

**Comment by matthewelse** [comment]
I'm going to work on documentation on my branch for the time being, otherwise I'll end up creating more and more prs.

**Comment by 0xc0170** [comment]
Ok, I'll keep an eye on your branch, and can do some help there ;)

**Comment by 0xc0170** [comment]
@matthewelse Once you return, can we look at docs? My focus for 0.7 is to deliver tests to cover basic functionality, documentation up to date in doc folder and some insight redesign which we started. Let me know what's the status - share the work with us, we can help

**Comment by 0xc0170** [comment]
I am starting writing new docs, will keep you posted.

**Comment by 0xc0170** [comment]
Let's keep wiki up to date, should be sufficient.
