### ISSUE TITLE
Tools should have own class (exporter, builder, flasher)

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#177]
tools are scattered in different layers. There should be tool classes like IAR, uVision, etc which define API for exporting, building and flashing.

I started doing this on my branch https://github.com/0xc0170/project_generator/tree/dev_iar_tool for IAR, to see how it will look and will do for uvision and see how much tools have in common.

cc @sarahmarshy @matthewelse @sg-

**Comment by matthewelse** [comment]
+1 this definitely makes sense

**Comment by 0xc0170** [comment]
Guys, I made some good progress. IAR file contains all within, definitions, IARWorkbench class defines export, build and flash methods, plus all additional sugar required.

**Comment by 0xc0170** [comment]
IAR and uvision done so far

**Comment by 0xc0170** [comment]
All tools were moved to tools/ dir.
