### ISSUE TITLE
More graceful failure of commands

### ISSUE THREAD

**Issue by matthewelse** [project-generator/project_generator#217]
We should make sure that instead of producing a traceback every time the user provides invalid/incorrect input, that we provide more useful warnings or errors. Tracebacks should be reserved for genuine bugs in the code.

**Comment by 0xc0170** [comment]
Reference #131, it's probably teh same one :-) We should come up with a better way of reporting it !

**Comment by 0xc0170** [comment]
What do you suggest to do instead of try: except Type: raise RuntimeError

**Comment by 0xc0170** [comment]
This is obsolete. If there is any failure which we can catch, create a new issue.
