### ISSUE TITLE
Continuous Integration Testing

### ISSUE THREAD

**Issue by matthewelse** [project-generator/project_generator#22]
I think that it would be fairly useful as a long term goal to have some sort of automated testing on the project generator.

**Comment by 0xc0170** [comment]
@sarahmashy, @matthewelse - something we should start doing soon ! AS now we unified a lot of things for 0.6, tests should be written to verify they work as we intend to :)

**Comment by 0xc0170** [comment]
I am closing this, the tests are slowly being added. Keep testing !
