### ISSUE TITLE
Relative paths broken?

### ISSUE THREAD

**Issue by sarahmarshy** [project-generator/project_generator#230]
If I define my export_dir outside of current project directory, IDE cannot find the files needed.

**Comment by 0xc0170** [comment]
Can you provide an example. What's the current project directory?

Be more specific, so I can reproduce this issue on my side.

**Comment by sarahmarshy** [comment]
```python
export_dir:
    -C:/users/sarmar01/Documents/pgen/tests/generated_projects
```

error in uvision:
cmsis_nvic.c: Error:  #5: cannot open source input file "..\..\..\..\..\..\..\..\..\..\mbed\libraries\mbed\targets\cmsis\TARGET_FREESCALE\TARGET_K20XX\TARGET_K20D50M\cmsis_nvic.c": No such file or directory

**Comment by sarahmarshy** [comment]
But export dir as normal 
```python
export_dir:
    -generated_projects
```
Works fine

**Comment by 0xc0170** [comment]
All paths for pgen are relative to the project directory. Pgen does not support absolute paths. we should probably warn a user using absolute paths?

**Comment by sarahmarshy** [comment]
Using:
```python
../generated_projects
```

does not seem to work either.

**Comment by 0xc0170** [comment]
Can you add a test case to tests, should fail and we fix to make it green :+1:

**Comment by sarahmarshy** [comment]
Here is fix in pgen_simple 

https://github.com/sarahmarshy/project_generator/commit/ccc61d64a24e29a531c97d65464a4b8cbdf6c997
