### ISSUE TITLE
Pgen init - generates files with hidden attributes

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#264]
I would argue that those files should be visible. This files are used during development and should not be hidden from a user.

@sg- @sarahmarshy

**Comment by sg-** [comment]
I think hidden is right. especially for single project use where these are auto generated. Doing Anything more advanced and you probably already have hidden files viewable on the OS

**Comment by 0xc0170** [comment]
Why would you hide them from a user? Even for single project. Have you seen any package manager to have files hidden? If a user/system wants, they can do it.

I don't think this is right for this type of files for a command pgen init, by default to be hidden.
