### ISSUE TITLE
Debugger settings do not work correctly in uVision 4

### ISSUE THREAD

**Issue by c1728p9** [project-generator/project_generator#276]
When initially loading project created for uVision the configured debugger does not work.  In the 'debug' tab in options the correct devices is selected yet the load button remains greyed out.  A workaround to fix this locally is to view the 'Utilities' tab and the press 'OK'.  This should be fixed so when a uVision project is opened for the first time everything just works.

**Comment by sg-** [comment]
This requires generating another file (uvopt) which store user config. I don't think this is a big deal and certainly not work the entire extra template file at the moment. Its just a side effect of simplicity.

**Comment by 0xc0170** [comment]
I don't think it requires uvopt to fix this bug. I believe it's just missing some settings. I found out that Utilities were not properly initialized for uvision4.
