### ISSUE TITLE
Uvision export picks wrong vendor with latest pgen

### ISSUE THREAD

**Issue by akselsm** [project-generator/project_generator#290]
After updating to pgen v0.7.6 with definitions v0.1.3, exporting a EFM32GG990F1024 project selects NXP as the vendor instead of Silicon Labs. Since Uvision does not know the "NXP EFM32GG990F1024", several error messages are shown.

@0xc0170

**Comment by 0xc0170** [comment]
#288 should fix that, I'll release a new patch for definitions and then merge this PR to fix that.

What errors are shown? Besides wrong vendor in the target tab, I have not experienced errors..

**Comment by akselsm** [comment]
Yep, it is fixed by #288 :)

**Comment by 0xc0170** [comment]
v0.7.7 should include the fix for this
