### ISSUE TITLE
init - creates non valid yaml syntax

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#373]
If run in any folder with some files, this is appended:

```
tool_specific: {}
```

**Comment by theotherjimmy** [comment]
That is valid Yaml for an empty map.
http://yaml.org/spec/1.1/#id932806
(the 1.2 spec is harder to read)

**Comment by 0xc0170** [comment]
Thanks for the reference. I don't recall why I created this issue if it was because then I could not use that yaml file (probably not), or just that personally I would remove it..
