### ISSUE TITLE
uvision - uvoptx generation

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#391]
Seems like uvision5 provides some additional info in the ``uvoptx`` file, similar to what we did for IAR ``ewd`` files. This might require an update of definitions or just use data we have there.

To enable this feature, we should get a python dic of uvoptx file, and find out which data there are required for debuggers (target and debugger specific).

Reference #339 for further info

cc @ohagendorf @adustm

**Comment by ohagendorf** [comment]
Maybe this can be closed now.

**Comment by 0xc0170** [comment]
thanks @ohagendorf
