### ISSUE TITLE
Duplicate C source files in generated project

### ISSUE THREAD

**Issue by LMESTM** [project-generator/project_generator#403]
Just want to share a problem I met yesterday: 
I used master branch (Merge pull request #399 from project-generator/dedupe-2-fn ) and the resulting project (a mbed project generated into a µvision project) contained a lot of duplicate source files and which resulted in build errors. I want back to a know working version 0.8.16 and this is working fine again.  The version I tested is not yet a released version, so not sure if this is relevant or not.

**Comment by 0xc0170** [comment]
It is definitely good to share, I am currently testing the master branch, not yet released the new version.

cc @theotherjimmy

**Comment by theotherjimmy** [comment]
It seems that the duplication is only in the .uvproj file, not in the source tree. I'm looking into why now.

**Comment by theotherjimmy** [comment]
That was silly of me. I think I squashed this bug. Thanks for reporting!

**Comment by theotherjimmy** [comment]
@LMESTM Could you test again?

**Comment by LMESTM** [comment]
I confirm there is no more duplication in .uvproj file so the project builds fine now, thanks for that !
.. but (sorry there is a minor but ;-) ) there are now empty directories visible in the project in µvision5. I think those  are directories where we can only find header files like hal/hal and hal/api in mbed. 
![image](https://cloud.githubusercontent.com/assets/17590297/16300086/4e665cb2-393e-11e6-8e75-061a61205d56.png)

**Comment by 0xc0170** [comment]
@LMESTM When you report a bug, please provide as much details as possible to reproduce it. What commands are you using ? to build and then to export, I just tried KL25Z MBED_10 project, I noticed another issues, but not empty directories. using the latest master on mbed and progen.

**Comment by 0xc0170** [comment]
Confirmed, I just rebased my progen branch, I can see those empty directories. We will fix it

**Comment by 0xc0170** [comment]
@LMESTM Should be resolved

**Comment by LMESTM** [comment]
@0xc0170  Indeed it works fine now - THX
