### ISSUE TITLE
TypeError: a bytes-like object is required, not `_io.TextIOWrapper`

### ISSUE THREAD

**Issue by jamesadevine** [project-generator/project_generator#407]
https://github.com/project-generator/project_generator/blob/master/project_generator/tools/uvision.py#L304

The above line fails when using python 3.

I've applied this fix to my installation:

```python
uvproj_dic = xmltodict.parse(open(template, encoding="utf8").read())
```
And it works!

I would form this into a PR, but I currently don't have the time!

**Comment by theotherjimmy** [comment]
I have your back on this one. I'll make the PR for you.

**Comment by theotherjimmy** [comment]
I'll even give you the credit, you did the heavy lifting on this one.

**Comment by 0xc0170** [comment]
Thanks for reporting and providing a fix !

**Comment by jamesadevine** [comment]
Thanks both! :smile:

**Comment by jamesadevine** [comment]
@theotherjimmy @0xc0170 I failed to realise that the "encoding" parameter fails on < python 3! 😱

**Comment by 0xc0170** [comment]
> @theotherjimmy @0xc0170 I failed to realise that the "encoding" parameter fails on < python 3! :scream:

Ehm, let me check the tests if that condition is not tested. I bet it's not as we have to run some tests on the real examples with real project templates. I have been exporting prior the release and did not have any failure.

**Comment by 0xc0170** [comment]
Anyway, the patch is wrong , this condition is not covered - https://github.com/theotherjimmy/project_generator/blob/4712c1d64d6cb2293ce16b6a044c767a26e8e420/project_generator/tools/uvision.py#L307

Thus I might have not spotted it while running local tests..
