### ISSUE TITLE
IAR debug broken

### ISSUE THREAD

**Issue by sarahmarshy** [project-generator/project_generator#422]
IAR debug does not work. I have found a solution: turning on the use of flash loaders (set in .ewd file). Is there a reason this was not enabled?

**Comment by 0xc0170** [comment]
What boards did you test? Various MCU vendors? like nxp, emf32, atmel etc?

I know that for instance nxp (freescale) boards require use flash loader to be enabled, but some others don't. Based on that, I assumed that this is a target specific, and we enabled .ewd templates.

**Comment by 0xc0170** [comment]
Thanks for raising this, this has been a known issue (I would like to understand those flashloaders better) that was not tracked.

**Comment by 0xc0170** [comment]
Any update to this issue?

**Comment by 0xc0170** [comment]
If yet not fixed, reopen via new issue.
