### ISSUE TITLE
Does this support to configure CMSIS-DAP serial number in Keil projects?

### ISSUE THREAD

**Issue by Hoohaha** [project-generator/project_generator#443]
As the title. Thanks very much.

**Comment by 0xc0170** [comment]
Hi,

this are the options that are used for debugger  : https://github.com/project-generator/project_generator/blob/master/project_generator/tools/uvision.py#L56 (line for cmsis). We do not set serial number. Does not that one come automatically ? 

What is the use case?

**Comment by Hoohaha** [comment]
There are several boards connected my PC, I want to automaticly generate the projects for each board, and then the projects will be built, then use Keil command line to download the image to board, if no serial number configured, the flash action will be failed. Because it default find the first index of boards.

I found a workaround: update bellow node
```xml      
<SetRegEntry>
          <Number>0</Number>
          <Key>CMSIS_AGDI</Key>
          <Name>-X"Any" -U -O206 -S0 -C0 -P00 -N00("ARM CoreSight SW-DP") -D00(0BD11477) -L00(0) -TO18 -TC10000000 -TP20 -TDS8007 -TDT0 -TDC1F -TIEFFFFFFFF -TIP8 -FO7 -FD1FFC0000 -FC1000 -FN1 -FF0MK_P2M0.FLM -FS00 -FL0200000 -FP0($$Device:MK28FN2M0VMI15$arm\MK_P2M0.FLM)</Name>
</SetRegEntry>
```
mbed_ls tool could list the connected boards, for example: the cmsis-dap number is 0226000040214e45001f1019c892004a9e11000097969900

```xml
-X"Any" -U0226000040214e45001f1019c892004a9e11000097969900 -O206 -S0 -C0 -P00 -N00("ARM CoreSight SW-DP") -D00(0BD11477) -L00(0) -TO18 -TC10000000 -TP20 -TDS8007 -TDT0 -TDC1F -TIEFFFFFFFF -TIP8 -FO7 -FD1FFC0000 -FC1000 -FN1 -FF0MK_P2M0.FLM -FS00 -FL0200000 -FP0($$Device:MK28FN2M0VMI15$arm\MK_P2M0.FLM)
```

**Comment by Hoohaha** [comment]
yes thanks a lot.
