### ISSUE TITLE
project_generator or progen: command not found

### ISSUE THREAD

**Issue by neilpanchal** [project-generator/project_generator#444]
Hello,
I downloaded the package using `pip install project_generator`. Installation completed successfully. 
However, I don't have the `progen` or `project_generator` command in bash. I get an error `command not found`. Could you please add some more instructions on how to add progen to path? Is there any executable available?

**Comment by 0xc0170** [comment]
Hi @neilpanchal , what is your OS you are running ? For windows, you need to have python scripts in your path for instance.

In my case, it is in Drive:/Python27/Scripts
