### ISSUE TITLE
Exporter Request: VS Code build using mbed-cli

### ISSUE THREAD

**Issue by 40Grit** [project-generator/project_generator#449]
@trowbidgec @farrenv

We have our own template for this, but having exporter would still be nice if we ever need to validate one of the stock examples with our boards.

**Comment by 0xc0170** [comment]
Hi @40Grit , do you have the template for sharing? I can have a look. 

As I understand, this request is for adding vs code template that uses mbed-cli? Is this part of Mbed OS exporters ?

**Comment by 40Grit** [comment]
We are going to stay using @janjongboom's exporter for this so I would start there.

**Comment by 40Grit** [comment]
*start using

**Comment by 40Grit** [comment]
https://github.com/janjongboom/mbed-vscode-generator

**Comment by 0xc0170** [comment]
@40Grit Would you be able to help adding this? I can help but not completely port currently. Otherwise this will be just without progress (I closed some old tool port requests recently).

**Comment by 40Grit** [comment]
No resources currently to add this into the OS. As Mbed Studio matures we will probably switch over.

Feel free to close unless @janjongboom has some insight proving it a straight forward task.
