### ISSUE TITLE
Tutorial introduction (Youtube link)

### ISSUE THREAD

**Issue by SuWeipeng** [project-generator/project_generator#450]
[youtube link](https://youtu.be/IM1bTqtLg4s)

**Comment by 0xc0170** [comment]
Hello @SuWeipeng . What is the video about? Without further description, this issue will be closed as not having sufficient details.

**Comment by 0xc0170** [comment]
Any update?

**Comment by SuWeipeng** [comment]
This is a simple tutorial. I do this because I think project_generator is a wonderful project.

**Comment by 0xc0170** [comment]
@SuWeipeng Thanks for the feedback!

I'll close this as it's not an issue. Thanks for sharing. Is it in chinese? Just checking
