### ISSUE TITLE
yaml error

### ISSUE THREAD

**Issue by SuWeipeng** [project-generator/project_generator#451]
errors
---
![4](https://user-images.githubusercontent.com/24380862/62406750-1b325d80-b5e3-11e9-99cb-06ddd0870a98.jpg)

how to solve
---
![1](https://user-images.githubusercontent.com/24380862/62406755-24bbc580-b5e3-11e9-84b0-59a448000d3e.jpg)
![2](https://user-images.githubusercontent.com/24380862/62406756-25545c00-b5e3-11e9-811a-7754edf75e83.jpg)
![3](https://user-images.githubusercontent.com/24380862/62406757-25545c00-b5e3-11e9-85a9-b0a4b960c6ce.jpg)

**Comment by 0xc0170** [comment]
@SuWeipeng Feel free to send PR or I can do it later. 

What version of pyaml you have installed? I'll try to update and reproduce the issue.

**Comment by SuWeipeng** [comment]
> @SuWeipeng Feel free to send PR or I can do it later.
> 
> What version of pyaml you have installed? I'll try to update and reproduce the issue.

New installation on windows with newest Python2.7, yaml version greater than 5.1

**Comment by 0xc0170** [comment]
> @SuWeipeng Feel free to send PR or I can do it later.

If you cand send PR with the fix, I shall find time to update my local packages and get this fix in otherwise

**Comment by 0xc0170** [comment]
I can reproduce the problem, will send Pr and test
