### ISSUE TITLE
how to generator .vscode folder and the config json files  

### ISSUE THREAD

**Issue by xuanxs** [project-generator/project_generator#481]
hello,dev
when generator the project,is that possible generate configuration file(such as launch.json,c_cpp_properties.json ..etc) in .vscode folder by the way. if it can‘t,will provide it in the next few versions?

PS: after generate the gcc  makefile，how to generate the linker file
![QQ截图20210121194856](https://user-images.githubusercontent.com/46104206/105347498-f6d89f80-5c21-11eb-9e79-98a880457956.png)

**Comment by 0xc0170** [comment]
> when generator the project,is that possible generate configuration file(such as launch.json,c_cpp_properties.json ..etc) in .vscode folder by the way. if it can‘t,will provide it in the next few versions?

What are these files ? I am not yet familiar with what vscode generates.

> PS: after generate the gcc makefile，how to generate the linker file

The error with `[]` seems like a bug - empty target in the makefile - the error is in yaml files - looks like something is missing. How can I reproduce the error?
