### ISSUE TITLE
Setting iar option 'GRuntimeLibSelect' state to 1 does not take effect

### ISSUE THREAD

**Issue by jsplyy** [project-generator/project_generator#489]
Hi,

I want to define the option 'GRuntimeLibSelect' for iar as semihosted, which should be const value 1 in iar project xml state filed.
I try to define this option in record file, but it seems that it does not work.

![image](https://user-images.githubusercontent.com/3600912/119826668-d94a7800-bf2a-11eb-9b78-9289f6f45ba1.png)

**Comment by 0xc0170** [comment]
I transferred it to project generator issue tracker.

**Comment by 0xc0170** [comment]
This is the default template https://github.com/project-generator/project_generator/blob/master/project_generator/templates/iar.ewp#L74
