### ISSUE TITLE
Support for "LLVM Embedded Toolchain for Arm"

### ISSUE THREAD

**Issue by mathias-arm** [project-generator/project_generator#503]
[LLVM Embedded Toolchain for Arm](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm) is a new LLVM-based toolchain, I have been considering adding support for. Maybe one question is how do we call it? `clang_arm` is a little bit confusing since `armclang` exists. `llvm_arm`?

**Comment by 0xc0170** [comment]
just reviewed the PR

`llvm_arm` sounds good as a name

**Comment by 0xc0170** [comment]
Thanks for adding it
