### ISSUE TITLE
The latest AC6 toolchain seems changes `armlinker` to `armlink`

### ISSUE THREAD

**Issue by mikisama** [project-generator/project_generator#508]
https://github.com/project-generator/project_generator/blob/d692a46b91177b7ac1ebc25484d4e1d23057420c/project_generator/templates/cmakelist_armclang.tmpl#L52

Hi,

I'm using MDK version 5.38, and the AC6 toolchain seems changes `armlinker` to `armlink`.

**Comment by 0xc0170** [comment]
Hi @mikisama ,can you send a new pull request to address this?
