### ISSUE TITLE
Use sh or other git python modules (pgen update)

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#82]
Currently for v0.5, we are using subprocess for pulling the latest mcu definitions. As it does not provide much options, going through pipes and all the other magic to get errors, we should consider module sh or any other available options.

It should rebase to the latest master silently (or might be faster to compare local HEAD and remote HEAD). The master should be available to change.. We support currently to redirect it to the local directory. Might consider also pull from a fork (but that's proably for later, I consder local directory to be a personal fork).

**Comment by matthewelse** [comment]
Sh looked like a really good choice, but seems like it's only supported on OSX and Linux, so alternatives are:

- Plumbumb (https://pypi.python.org/pypi/plumbum)
... I can't find any more - I'll edit this if I can find any more

**Comment by 0xc0170** [comment]
WE might just go ahead with subprocess as it is, just do more magic there, as I noted. If definitions have local commits -> print a warning for example

**Comment by 0xc0170** [comment]
I added handling if definitions HEAD is behind origin/master, then debug message is print and they are rebased. The update needs much more work, to process correctly outputs from git to provide some output what has happened.

**Comment by 0xc0170** [comment]
Obsolete
