### ISSUE TITLE
Improve list command

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#94]
We should be able to provide users a feedback, to list projects available, to list targets. to list tools.

A code example:
```
#print projects
pgen list projects
#print targets
pgen list targets
#print tools
pgen list tools
```

Currently, list is for list projects only.

**Comment by 0xc0170** [comment]
If we can get info from projects , we could expand above - if project file is defined , read that and provide a list from the projects file, otherwise provide info from pgen.

what do you think?

**Comment by sarahmarshy** [comment]
This is implemented. 
#prints all projects
pgen list / pgen list projects
#prints all available tools
pgen list tools
#prints tools in specifiec project file
pgen list tools -f your_project_file.yaml
#prints all available targets
pgen list targets
#prints targets in specifiec project file
pgen list targets -f your_project_file.yaml

**Comment by 0xc0170** [comment]
@sarahmarshy pgen list projects - what should this pring ? If no -f is provided? currently there's no output.

**Comment by sarahmarshy** [comment]
It shouldn't print anything. What would be logical output?
